export const refs = {
  gallery: document.querySelector('.card-list-container'),
  header: document.getElementById('header'),
  onHomeBtn: document.getElementById('home-btn'),
  onLibraryBtn: document.getElementById('library-btn'),
  inputContainer: document.getElementById('input__container'),
  libraryBtnContainer: document.getElementById('library__container'),
  userInput: document.getElementById('user-input'),
  onWatchedBtn: document.getElementById('watched'),
  onQueueBtn: document.getElementById('queue'),
  li: document.querySelector('.movie-card'),
  lightbox: document.querySelector('div.lightbox'),
  lightboxOverlay: document.querySelector('.lightbox__overlay'),
  lightboxContent: document.querySelector('.lightbox__content'),
  closeBnt: document.querySelector('[data-action=close-lightbox]'),
  inputEl: document.querySelector('#user-input'),
  inputWrapperEl: document.querySelector('.input__container'),
  footerEl: document.querySelector('.footer'),
};
